CREATE TABLE IF NOT EXISTS schema_migrations (version TEXT PRIMARY KEY, applied_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS memory (tier TEXT NOT NULL, key TEXT NOT NULL, value JSONB NOT NULL, updated_at TIMESTAMPTZ NOT NULL, PRIMARY KEY (tier,key));
CREATE INDEX IF NOT EXISTS idx_memory_cold_action ON memory USING GIN (value) WHERE tier='COLD';
CREATE INDEX IF NOT EXISTS idx_memory_warm_shape ON memory USING GIN (value) WHERE tier='WARM';
CREATE TABLE IF NOT EXISTS journal (seq BIGSERIAL PRIMARY KEY, event_id TEXT NOT NULL UNIQUE, created_at TIMESTAMPTZ NOT NULL, event TEXT NOT NULL, payload JSONB NOT NULL);
CREATE TABLE IF NOT EXISTS orders (id TEXT PRIMARY KEY, client_order_id TEXT NOT NULL UNIQUE, decision_id TEXT NOT NULL, mode TEXT NOT NULL, market_id TEXT NOT NULL, side TEXT NOT NULL, requested_size DOUBLE PRECISION NOT NULL, limit_price DOUBLE PRECISION NOT NULL, status TEXT NOT NULL, filled_size DOUBLE PRECISION NOT NULL DEFAULT 0, filled_notional DOUBLE PRECISION NOT NULL DEFAULT 0, average_fill_price DOUBLE PRECISION, venue_order_id TEXT, error TEXT, created_at TIMESTAMPTZ NOT NULL, updated_at TIMESTAMPTZ NOT NULL);
CREATE INDEX IF NOT EXISTS idx_orders_decision ON orders(decision_id);
CREATE INDEX IF NOT EXISTS idx_orders_status ON orders(status);
CREATE TABLE IF NOT EXISTS security_keys (key_digest TEXT PRIMARY KEY, key_id TEXT NOT NULL UNIQUE, scope TEXT NOT NULL, active BOOLEAN NOT NULL DEFAULT TRUE, created_at TIMESTAMPTZ NOT NULL, revoked_at TIMESTAMPTZ);
CREATE INDEX IF NOT EXISTS idx_security_keys_active ON security_keys(active);
CREATE TABLE IF NOT EXISTS security_rate_limits (principal TEXT NOT NULL, route TEXT NOT NULL, window_start TIMESTAMPTZ NOT NULL, request_count INTEGER NOT NULL DEFAULT 0, PRIMARY KEY(principal,route));
CREATE TABLE IF NOT EXISTS verified_market_inputs (snapshot_hash TEXT PRIMARY KEY, market_id TEXT NOT NULL, input_hash TEXT NOT NULL, payload JSONB NOT NULL, observed_at TIMESTAMPTZ NOT NULL);
CREATE INDEX IF NOT EXISTS idx_verified_inputs_market ON verified_market_inputs(market_id,observed_at);
CREATE TABLE IF NOT EXISTS market_snapshots (id BIGSERIAL PRIMARY KEY, market_id TEXT NOT NULL, observed_at TIMESTAMPTZ NOT NULL, payload JSONB NOT NULL, payload_hash TEXT NOT NULL UNIQUE);
CREATE INDEX IF NOT EXISTS idx_market_snapshots_observed ON market_snapshots(observed_at);
CREATE TABLE IF NOT EXISTS market_observations (id BIGSERIAL PRIMARY KEY, market_id TEXT NOT NULL, observed_at TIMESTAMPTZ NOT NULL, payload_hash TEXT NOT NULL, valid BOOLEAN NOT NULL, validation_reason TEXT, book_valid BOOLEAN NOT NULL DEFAULT FALSE, book_sequence BIGINT);
CREATE INDEX IF NOT EXISTS idx_market_observations_observed ON market_observations(observed_at);
CREATE TABLE IF NOT EXISTS pipeline_health (id INTEGER PRIMARY KEY, last_tick_at TIMESTAMPTZ, last_success_at TIMESTAMPTZ, last_error_at TIMESTAMPTZ, last_error TEXT, error_count INTEGER NOT NULL DEFAULT 0, last_markets INTEGER NOT NULL DEFAULT 0, last_books INTEGER NOT NULL DEFAULT 0, last_resolution_at TIMESTAMPTZ, last_resolved INTEGER NOT NULL DEFAULT 0, last_resolution_errors INTEGER NOT NULL DEFAULT 0, last_pending INTEGER NOT NULL DEFAULT 0);
INSERT INTO pipeline_health(id) VALUES (1) ON CONFLICT (id) DO NOTHING;
CREATE TABLE IF NOT EXISTS resolution_retries (market_id TEXT PRIMARY KEY, attempts INTEGER NOT NULL DEFAULT 0, next_retry_at TIMESTAMPTZ NOT NULL, last_error TEXT, updated_at TIMESTAMPTZ NOT NULL);
CREATE INDEX IF NOT EXISTS idx_resolution_retries_due ON resolution_retries(next_retry_at);
CREATE TABLE IF NOT EXISTS runtime_config (key TEXT PRIMARY KEY, value JSONB NOT NULL, version BIGINT NOT NULL, updated_by TEXT NOT NULL, updated_at TIMESTAMPTZ NOT NULL);
CREATE TABLE IF NOT EXISTS runtime_config_history (version BIGSERIAL PRIMARY KEY, changes JSONB NOT NULL, previous JSONB NOT NULL, updated_by TEXT NOT NULL, reason TEXT NOT NULL, updated_at TIMESTAMPTZ NOT NULL);
CREATE INDEX IF NOT EXISTS idx_runtime_config_history_updated ON runtime_config_history(updated_at DESC);
