ALTER TABLE orders ADD COLUMN IF NOT EXISTS filled_notional DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE pipeline_health ADD COLUMN IF NOT EXISTS last_resolution_at TIMESTAMPTZ;
ALTER TABLE pipeline_health ADD COLUMN IF NOT EXISTS last_resolved INTEGER NOT NULL DEFAULT 0;
ALTER TABLE pipeline_health ADD COLUMN IF NOT EXISTS last_resolution_errors INTEGER NOT NULL DEFAULT 0;
ALTER TABLE pipeline_health ADD COLUMN IF NOT EXISTS last_pending INTEGER NOT NULL DEFAULT 0;
ALTER TABLE live_kill_switch ADD COLUMN IF NOT EXISTS phase TEXT NOT NULL DEFAULT 'RUNNING';
